# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2d9b9231304105b1c6d2fd821aa36ed390425b533631c63886d4209d88f9fec794025872e628203b85164a16bd9fccaf8148545c8453ce24a425508d61e50d1

test:
  secret_key_base: 825f66bc1d9d24388aa33f30f350725586452a2fc81eb4c260674130001de1f6a4190a71d58f9e440603223b11c9cb5808fe04bb1e3465772e30750cefdadd67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
